rearrange

diff --git a/src/bam2bedgraph/RUN_C b/src/bam2bedgraph/RUN_C
--- a/src/bam2bedgraph/RUN_C
+++ b/src/bam2bedgraph/RUN_C
@@ -22,54 +22,37 @@ if [ "${1}" == "" -o "${3}" == "" ]; then
  exit 
 fi
 
-export BED_SITESHIFT=0
+export BED_SITESHIFT=75
 export BED_WINDOW=200
 export TYPE=DNA
 
 case ${1} in
-  "-bedtophatmsql")
+  *tophat*)
+   export BED_SITESHIFT=0
    export TYPE=RNA
+   export BED_WINDOW=20
   ;;
-  "-dotophat")
-   export TYPE=RNA
+  *pair*)
+   export BED_SITESHIFT=0
   ;;
-  "-bedmsql")
-   export BED_SITESHIFT=75
-  ;;
-  "-bedmsql_pair")
-  ;;
-  "-bowtiehits")
-  ;; 
-  "-bowtiebam")
-   export BED_SITESHIFT=75
-  ;;
-  "-dosicer")
-  ;;
-  "-doquest")
-  ;;
-  "-doaverage")
-  ;;
-  *)
-   echo "Unknown type"
-  exit
 esac
 
 
 export RUN_ON="${3}" #
 
 #export GROUP="joe"
+export BED_FORMAT=4 # 4/8
 
-export TOPHAT_TRANSCRIPTOME_ONLY=" --no-novel-juncs "
 case ${2} in
   "MARK")
     export GROUP="marcroch"
    #export GROUP="markroch1"
-    export TOPHAT_TRANSCRIPTOME_ONLY=" --no-novel-juncs -T "
+    export ADD_TOPHAT=" -T "
   ;;
   "YRINA")
    export GROUP="barskii2"
-   export TOPHAT_TRANSCRIPTOME_ONLY=" --no-novel-juncs "
-   export DUTP=" --library-type fr-firststrand "
+   export ADD_TOPHAT=" --library-type fr-firststrand " #DUTP
+   export BED_FORMAT=8
   ;;
   "BARSKI")
    export GROUP="barskii2"
@@ -79,6 +62,9 @@ case ${2} in
   ;;
   "SATOSHI")
    export GROUP="NamekawaSatoshi"
+  ;;
+  "FILIPI")
+   export GROUP="filipi"
   ;;
   "NIH")
    export GROUP="barskii5" #CD4 substets RNA-seq
@@ -90,6 +76,7 @@ case ${2} in
   ;;
   "RAHUL")
    export GROUP="rahul"
+   export ADD_TOPHAT=" -T "
   ;;
   *)
   echo "Unknown name"
@@ -101,33 +88,15 @@ esac
 export WORK_DIR="/data/DATA/FASTQ-DATA/${2}/${TYPE}"
 
 
-#export WORK_DIR="/data/DATA/FASTQ-DATA/SARA/"
-#export WORK_DIR="/data/DATA/FASTQ-DATA/MARK/DNA/"
-#export WORK_DIR="/data/DATA/FASTQ-DATA/MARK/RNA/"
-#export WORK_DIR="/data/DATA/FASTQ-DATA/MARK/PAPER1/RNA/"
-#export WORK_DIR="/data/DATA/FASTQ-DATA/JOE/RNA/"
-#export WORK_DIR="/data/DATA/FASTQ-DATA/RAHUL/RNA/"
-#export WORK_DIR="/data/DATA/FASTQ-DATA/CLARK"
-#export WORK_DIR="/data/DATA/FASTQ-DATA/YRINA/RNA"
-#export WORK_DIR="/data/DATA/FASTQ-DATA/NamekawaSatoshi/DNA"
-#export WORK_DIR="/data/DATA/FASTQ-DATA/Olsson/"
-#export WORK_DIR="/data/DATA/FASTQ-DATA/TEST/"
-#export WORK_DIR="/data/DATA/FASTQ-DATA/NIH/RNA"
-#export WORK_DIR="/data/DATA/FASTQ-DATA/CLARK/DNA"
-
-#export TRIM="-5 6"
 
 #export RUN_ON="rebo" #
 #export RUN_ON="hg19c" #
 #export RUN_ON="hg19" #
 #export RUN_ON="mm9" #
-#export DUTP="--library-type fr-firststrand"
-#--max-deletion-length 20 --segment-length 20
 
-export ADD_TOPHAT=" -g 1 ${DUTP} ${TOPHAT_TRANSCRIPTOME_ONLY} ${ADD_TOPHAT} "
-export BED_FORMAT=4 # 4/8
+# "-5 6" #- tophat trim 6 bases from 5'
+export ADD_TOPHAT=" -g 1 --no-novel-juncs ${ADD_TOPHAT} "
 
-#--no-novel-juncs 
 case ${RUN_ON} in 
  "hg19")
    export GENOME=hg19
@@ -136,17 +105,17 @@ case ${RUN_ON} in
 #   export TRANSCRIPTOME=" --transcriptome-index ${BOWTIE_INDEXES}/hg19_genes"
 #   export GFT_FILE="-G ${BOWTIE_INDEXES}/gtf/hg19_genes.gtf"
  ;;
- "mm9")
-   export GENOME=mm9
-   export SQLDB="-sql_dbname=mm9"
-   export GFT_FILE=" -G ${BOWTIE_INDEXES}/mm9_genes.gtf "
-   export TRANSCRIPTOME=" --transcriptome-index ${BOWTIE_INDEXES}/gtf/mm9_genes "
- ;;
  "hg19c")
    export GENOME=hg19c
    export GFT_FILE=" -G ${BOWTIE_INDEXES}/gtf/hg19_refsec_genes_control.gtf "
-   #export TRANSCRIPTOME=" --transcriptome-index ${BOWTIE_INDEXES}/gtf/hg19_refsec_genes_control "
-   export TRANSCRIPTOME=" --keep-tmp  "
+   export TRANSCRIPTOME=" --transcriptome-index ${BOWTIE_INDEXES}/gtf/hg19_refsec_genes_control "
+ ;;
+ "mm9")
+   export GENOME=mm9
+   export SQLDB=" -sql_dbname=mm9 "
+   export GFT_FILE=" -G ${BOWTIE_INDEXES}/mm9_genes.gtf "
+#   export TRANSCRIPTOME=" --transcriptome-index ${BOWTIE_INDEXES}/gtf/mm9_genes "
+    export TRANSCRIPTOME=" --keep-tmp  "
  ;;
  "hg19_lupus")
    export GENOME=hg19_lupus
@@ -193,7 +162,9 @@ case ${1} in
     $ZC ${ZNA}|${BOWTIE_PATH} -q -v 2 -m 1 --best --strata -p 24 -S ${TRIM} \
     ${GENOME} - 2>./${NA}${SUFFIX}.bw.log|
     samtools view -Sb - >./${NA}${SUFFIX}.bam 2>/dev/null
-    echo "Making .bam complete"
+    res=$?
+    echo "Making .bam complete $res"
+    return $res
    fi
   ;;
   "hits")
@@ -259,7 +230,9 @@ FNAME="${NA}_${c}"
     ${TOPHAT_PATH} --num-threads 24 -o ${FNAME} ${GFT_FILE} ${ADD_TOPHAT} ${TRANSCRIPTOME} ${BOWTIE_INDEXES}/${GENOME} ${NA}
 
     mv ./${FNAME}/accepted_hits.bam ./${NA}.bam
-    echo "Making .bam by tophat complete"
+    res=$?
+    echo "Making .bam by tophat complete $res"
+    return $res
    fi
 }
 
@@ -271,9 +244,12 @@ FNAME="${NA}_${c}"
 function upload_bed_mysql {
 
  do_bw_bam "bam"
-
- bam2bedgraph -sql_table="${TBLN}" -bed_trackname="${TBL}" -in="${NA}.bam" -out="${NA}.out" -log="${NA}.log" \
- -sql_grp="${GROUP}" -bed_window=${BED_WINDOW} -bed_siteshift=${BED_SITESHIFT} -bed_format=${BED_FORMAT} -no-bed-file  ${SQLDB}
+ if [ $? -eq 0 ]; then
+  bam2bedgraph -sql_table="${TBLN}" -bed_trackname="${TBL}" -in="${NA}.bam" -out="${NA}.out" -log="${NA}.log" \
+   -sql_grp="${GROUP}" -bed_window=${BED_WINDOW} -bed_siteshift=${BED_SITESHIFT} -bed_format=${BED_FORMAT} -no-bed-file  ${SQLDB}
+ else
+  echo "Error making bam file"
+ fi
 }
 
 function upload_bed_mysql_pair {
@@ -291,9 +267,22 @@ function upload_bed_mysql_pair {
 function upload_tophat_bed_mysql {
 
  do_tophat_bam
-
- bam2bedgraph -sql_table="${TBLN}" -in="${NA}.bam" -out="${NA}.out" -log="${NA}.log" -bed_trackname="${TBL}" \
-  -sql_grp="${GROUP}" -bed_window=${BED_WINDOW} -bed_format=${BED_FORMAT} -no-bed-file ${SQLDB}
+ res=$?
+ echo "Debug tophat return $res"
+ 
+ if [ $res -eq 0 ]; then
+ 
+  bam2bedgraph -sql_table="${TBLN}" -in="${NA}.bam" -out="${NA}.out" -log="${NA}.log" -bed_trackname="${TBL}" \
+   -sql_grp="${GROUP}" -bed_window=${BED_WINDOW} -bed_format=${BED_FORMAT} -no-bed-file ${SQLDB}
+  if [ $? -eq 0 ]; then
+   LC=`wc -l ${NA}|awk '{print $1/4}'`
+   grep 'Aligned:' ${NA}.log |awk -v tot=${LC} -F'Aligned: ' '{printf("Total: %d\nAligned: %d\nPercent: %f\n",tot,$2,$2*100/tot);}' >${NA}.stat
+  else
+   echo "Error uploading tophat bed"   
+  fi
+ else
+  echo "Error in making tophat bam"
+ fi
 }
 
 
@@ -313,9 +302,6 @@ function do_average {
 function do_sicer {
  do_bw_bam "bam"
 
- echo "do sicer not done yet"
- exit 
-
  T=1
  W=200
  G=200
@@ -324,9 +310,6 @@ function do_sicer {
  if [ -f "./${NA}_s.bed" ]; then
   echo "${NA}_s.bed exist"
  else
-#  ${REPO_BASE}/genomebrowser/src/bam2bedgraph/bam2bedgraph -in="${NA}.bam" -out="${NA}_s.bed" -log="${NA}_s.log" -bed_window=0 -bed_format=8 -no-sql-upload -sam_mapped_limit=0
-#  grep -v 'track' ${NA}_s.bed|awk '{ if($4<0) $4=$4*(-1); printf("%s\t%s\t%s\tU%s\t%s\t%s\n",$1,$2,$3,$5,$4,$6);}' >${NA}_so.bed
-#  mv -f ${NA}_so.bed ${NA}_s.bed
   if [ ${LIMIT} -gt 0 ]; then
    bamToBed -bed12 -i ${NA}.bam |head -${LIMIT} >./${NA}_s.bed
   else
@@ -339,12 +322,12 @@ function do_sicer {
  if [ -f "./SICER/${NA}_s-W${W}-G${G}-E${E}.scoreisland" ]; then
   echo "./SICER/${NA}_s-W${W}-G${G}-E${E}.scoreisland exist"
   cd ./SICER
-  ${REPO_BASE}/genomebrowser/scripts/BedLoaderSicer.py ${NA} ${GROUP} hg19
+  #BedLoaderSicer.py ${NA} ${GROUP} hg19
   cd ..
  else
   mkdirhier ./SICER/
-#  sh ${REPO_BASE}/genomebrowser/thirdparty/SICER1.1/SICER/SICER-rb.sh . ${NA}_s.bed ./SICER hg19 1 50 150 0.74 50 0.1
-  SICER-rb.sh . ${NA}_s.bed ./SICER hg19 ${T} ${W} 150 0.74 ${G} ${E}
+  #sh ${REPO_BASE}/genomebrowser/thirdparty/SICER1.1/SICER/SICER-rb.sh . ${NA}_s.bed ./SICER hg19 1 50 150 0.74 50 0.1
+  SICER-rb.sh . ${NA}_s.bed ./SICER $GENOME ${T} ${W} 150 0.74 ${G} ${E}
  fi
  
 # cd ./SICER/
@@ -385,8 +368,8 @@ function do_fence {
  if [ -f ./${1}.fence ]; then
   echo "${1}.fence exist"
  else 
-  fence.py --in=${NA} >${NA}.fence
-  echo "Making ${1}.fence complete"
+  fence.py --in=${NA} >${NA}.fence &
+  echo "Making ${1}.fence backgrounded"
  fi
 
 }
@@ -430,7 +413,7 @@ echo "${i}"|grep -v "^#" >/dev/null
 
  cd ${WORK_DIR} #/${NA}/
 
- #do_fence "${NA}"
+ do_fence "${NA}"
 
 
 case ${1} in
