pipeline polishing

diff --git a/src/bam2bedgraph/RUN_C b/src/bam2bedgraph/RUN_C
--- a/src/bam2bedgraph/RUN_C
+++ b/src/bam2bedgraph/RUN_C
@@ -2,9 +2,102 @@
 
 export BOWTIE_INDEXES="/data/DATA/indexes"
 
+if [ "${1}" == "" -o "${3}" == "" ]; then
+  echo "
+ Programm usage:"
+  echo " 
+ $0 -bedtophatmsql <OPTIONS>
+ $0 -dotophat <OPTIONS>
+ $0 -bedmsql <OPTIONS>
+ $0 -bedmsql_pair <OPTIONS>
+ $0 -bowtiehits <OPTIONS>
+ $0 -bowtiebam <OPTIONS>
+ $0 -dosicer <OPTIONS>
+ $0 -doquest <OPTIONS>
+ $0 -doaverage <OPTIONS>
 
-#export WORK_DIR="/data/DATA/FASTQ-DATA/Experiments-2012/DNA"
-#export WORK_DIR="/data/DATA/FASTQ-DATA/Experiments-2012/YRINA/"
+  OPTIONS:
+   <NAME> <GENOME>
+  "
+ exit 
+fi
+
+export BED_SITESHIFT=0
+export BED_WINDOW=200
+export TYPE=DNA
+
+case ${1} in
+  "-bedtophatmsql")
+   export TYPE=RNA
+  ;;
+  "-dotophat")
+   export TYPE=RNA
+  ;;
+  "-bedmsql")
+   export BED_SITESHIFT=75
+  ;;
+  "-bedmsql_pair")
+  ;;
+  "-bowtiehits")
+  ;; 
+  "-bowtiebam")
+   export BED_SITESHIFT=75
+  ;;
+  "-dosicer")
+  ;;
+  "-doquest")
+  ;;
+  "-doaverage")
+  ;;
+  *)
+   echo "Unknown type"
+  exit
+esac
+
+
+export RUN_ON="${3}" #
+
+#export GROUP="joe"
+#export GROUP="rahul"
+
+export TOPHAT_TRANSCRIPTOME_ONLY=" --no-novel-juncs "
+case ${2} in
+  "MARK")
+    export GROUP="marcroch"
+   #export GROUP="markroch1"
+    export TOPHAT_TRANSCRIPTOME_ONLY=" --no-novel-juncs -T "
+  ;;
+  "YRINA")
+   export GROUP="barskii2"
+   export TOPHAT_TRANSCRIPTOME_ONLY=" --no-novel-juncs "
+   export DUTP=" --library-type fr-firststrand "
+  ;;
+  "BARSKI")
+   export GROUP="barskii2"
+  ;;
+  "CLARK")
+   export GROUP="barskii2"
+  ;;
+  "SATOSHI")
+   export GROUP="NamekawaSatoshi"
+  ;;
+  "NIH")
+   export GROUP="barskii5" #CD4 substets RNA-seq
+   #export GROUP="barskii4" #CD4 substets chromatin
+  ;;
+  "TEST")
+   export GROUP="test"
+  ;;
+  *)
+  echo "Unknown name"
+  exit
+  ;;
+esac
+
+
+export WORK_DIR="/data/DATA/FASTQ-DATA/${2}/${TYPE}"
+
+
 #export WORK_DIR="/data/DATA/FASTQ-DATA/SARA/"
 #export WORK_DIR="/data/DATA/FASTQ-DATA/MARK/DNA/"
 #export WORK_DIR="/data/DATA/FASTQ-DATA/MARK/RNA/"
@@ -13,34 +106,21 @@ export BOWTIE_INDEXES="/data/DATA/indexes"
 #export WORK_DIR="/data/DATA/FASTQ-DATA/RAHUL/RNA/"
 #export WORK_DIR="/data/DATA/FASTQ-DATA/CLARK"
 #export WORK_DIR="/data/DATA/FASTQ-DATA/YRINA/RNA"
-#export WORK_DIR="/data/DATA/FASTQ-DATA/Barski/NIH/CD4-CTCF"
-#export WORK_DIR="/data/DATA/FASTQ-DATA/Barski_OLD"
 #export WORK_DIR="/data/DATA/FASTQ-DATA/NamekawaSatoshi/DNA"
 #export WORK_DIR="/data/DATA/FASTQ-DATA/Olsson/"
 #export WORK_DIR="/data/DATA/FASTQ-DATA/TEST/"
-export WORK_DIR="/data/DATA/FASTQ-DATA/NIH/RNA"
+#export WORK_DIR="/data/DATA/FASTQ-DATA/NIH/RNA"
+#export WORK_DIR="/data/DATA/FASTQ-DATA/CLARK/DNA"
 
-
-#export GROUP="barskii2"
-export GROUP="barskii5" #CD4 substets RNA-seq
-#export GROUP="barskii4" #CD4 substets chromatin
-#export GROUP="marcroch"
-#export GROUP="markroch1"
-#export GROUP="NamekawaSatoshi"
-#export GROUP="joe"
-#export GROUP="rahul"
-#export GROUP="test"
-
-export BED_SITESHIFT=0
-export BED_WINDOW=20
 #export TRIM="-5 6"
 
 #export RUN_ON="rebo" #
 #export RUN_ON="hg19c" #
-export RUN_ON="hg19" #
+#export RUN_ON="hg19" #
 #export RUN_ON="mm9" #
 #export DUTP="--library-type fr-firststrand"
-export TOPHAT_TRANSCRIPTOME_ONLY=" --no-novel-juncs "
+#--max-deletion-length 20 --segment-length 20
+
 export ADD_TOPHAT=" -g 1 ${DUTP} ${TOPHAT_TRANSCRIPTOME_ONLY} "
 export BED_FORMAT=4 # 4/8
 
@@ -49,28 +129,28 @@ case ${RUN_ON} in
  "hg19")
    export GENOME=hg19
    echo ${BOWTIE_INDEXES}
-#   export TRANSCRIPTOME="--transcriptome-index ${BOWTIE_INDEXES}/hg19_genes"
-   export TRANSCRIPTOME="--transcriptome-index ${BOWTIE_INDEXES}/gtf/hg19_refsec_genes"
-#   export GFT_FILE="-G /data/barskilab/indexes/hg19_genes.gtf"
+   export TRANSCRIPTOME=" --transcriptome-index ${BOWTIE_INDEXES}/gtf/hg19_refsec_genes "
    export GFT_FILE="-G ${BOWTIE_INDEXES}/gtf/hg19_refsec_genes.gtf"
+#   export TRANSCRIPTOME=" --transcriptome-index ${BOWTIE_INDEXES}/hg19_genes"
+#   export GFT_FILE="-G ${BOWTIE_INDEXES}/gtf/hg19_genes.gtf"
  ;;
  "mm9")
    export GENOME=mm9
    export SQLDB="-sql_dbname=mm9"
-   export GFT_FILE="-G ${BOWTIE_INDEXES}/mm9_genes.gtf"
-   export TRANSCRIPTOME="--transcriptome-index ${BOWTIE_INDEXES}/gtf/mm9_genes"
+   export GFT_FILE=" -G ${BOWTIE_INDEXES}/mm9_genes.gtf "
+   export TRANSCRIPTOME=" --transcriptome-index ${BOWTIE_INDEXES}/gtf/mm9_genes "
  ;;
  "hg19c")
    export GENOME=hg19c
-   export GFT_FILE="-G ${BOWTIE_INDEXES}/hg19_refsec_genes_control.gtf"
-   export TRANSCRIPTOME="--transcriptome-index ${BOWTIE_INDEXES}/gtf/hg19_refsec_genes_control"
+   export GFT_FILE=" -G ${BOWTIE_INDEXES}/gtf/hg19_refsec_genes_control.gtf "
+   export TRANSCRIPTOME=" --transcriptome-index ${BOWTIE_INDEXES}/gtf/hg19_refsec_genes_control "
+#   export TRANSCRIPTOME=" --keep-tmp  "
  ;;
  "hg19_lupus")
    export GENOME=hg19_lupus
  ;;
  "rebo")
    export GENOME=rebo
-#   export GFT_NAME=rebo
    export SUFFIX="_rebo"
  ;;
  *)
@@ -108,7 +188,7 @@ case ${1} in
    if [ -f ./${NA}${SUFFIX}.bam ]; then
     echo "${NA}${SUFFIX}.bam exist"
    else 
-    $ZC ${ZNA}|${BOWTIE_PATH} -q -v 2 -m 1 --best --strata -p 11 -S ${TRIM} \
+    $ZC ${ZNA}|${BOWTIE_PATH} -q -v 2 -m 1 --best --strata -p 24 -S ${TRIM} \
     ${GENOME} - 2>./${NA}${SUFFIX}.bw.log|
     samtools view -Sb - >./${NA}${SUFFIX}.bam 2>/dev/null
     echo "Making .bam complete"
@@ -118,7 +198,7 @@ case ${1} in
     if [ -f ./${NA}${SUFFIX}.hits -o -f ./${NA}${SUFFIX}.hits.gz ]; then
      echo "${NA}${SUFFIX}.hits exist"
     else 
-     $ZC ${ZNA}|${BOWTIE_PATH} -q -v 2 -m 1 --best --strata -p 11 ${TRIM} \
+     $ZC ${ZNA}|${BOWTIE_PATH} -q -v 2 -m 1 --best --strata -p 24 ${TRIM} \
      ${GENOME} - 2>./${NA}${SUFFIX}.bw_h.log >./${NA}${SUFFIX}.hits
      echo "Making .hits complete"
    fi
@@ -170,7 +250,6 @@ export c=1
 while [ -d ${NA}_${c} ]; do  let c=$c+1; done
 
 FNAME="${NA}_${c}"
-#--max-deletion-length 20 --segment-length 20
 
    if [ -f ./${NA}.bam ]; then
     echo "${NA}.bam exist"
@@ -184,44 +263,15 @@ FNAME="${NA}_${c}"
 
 
 #
-#do bed for sicer, just for upload
-#
-
-function do_bed_file {
-
- echo "depricated"
-# if [ -f ./${1}.bed ]; then
-#  echo "${1}.bed exist"
-# else 
-#  rm -f ./logfile.log
-#  ${REPO_BASE}/genome-tools/src/sam2bedgraph/sam2bedgraph ${NA}.bam
-#  mv -f output.bed ./${1}.bed
-#  echo "Making ${1}.bed complete"
-# fi
-
-}
-
-
-#
 # if bam file does not exist for fastq file it generates by bowtie in the same directory
-# function for uploading generated by sam2bedgraph files into genome browser
+# function for uploading generated bams by bam2bedgraph into genome browser
 #
 function upload_bed_mysql {
 
  do_bw_bam "bam"
- #replace +,=,-,\. on _
-# TBL="${NA//[+|=|\-|\.]/_}"
-# TBL="${TBL//run*index[0-9]_/}"
-# TBL="${TBL//_fastq}"
- bam2bedgraph -sql_table="${TBL}" -in="${NA}.bam" -out="${NA}.out" -log="${NA}.log" \
+
+ bam2bedgraph -sql_table="${TBLN}" -bed_trackname="${TBL}" -in="${NA}.bam" -out="${NA}.out" -log="${NA}.log" \
  -sql_grp="${GROUP}" -bed_window=${BED_WINDOW} -bed_siteshift=${BED_SITESHIFT} -bed_format=${BED_FORMAT} -no-bed-file  ${SQLDB}
- 
-#"debug/bam2bedgraph.exe" -in="run0146_lane8_read1_index10=ABYR21.fastq.bam" -out="run0146_lane8_read1_index10=ABYR21.fastq.out" -bed_window=20 -bed_siteshift=0 -bed_format=8 -log="run0146_lane8_read1_index10=ABYR21.fastq.log" -sql_table="run0146_lane8_read1_index10_ABYR21" -sql_grp="barskii2" -rna_seq="dUTP" -no-bed-file
- 
- 
-# do_bed_file "${NA}"
-# ${REPO_BASE}/genome-tools/scripts/BedLoader.py ${NA} ${GROUP} ${GENOME}
- 
 }
 
 function upload_bed_mysql_pair {
@@ -232,6 +282,10 @@ function upload_bed_mysql_pair {
 # ${REPO_BASE}/genome-tools/src/bam2bedgraph/bam2bedgraph -sql_table="${TBL}" -in="${NA}.bam" -out="${NA}.out" -log="${NA}.log" -sql_grp="${GROUP}" -bed_window=${BED_WINDOW} -bed_siteshift=${BED_SITESHIFT} -bed_format=${BED_FORMAT} -no-bed-file  ${SQLDB}
 }
 
+#
+# if bam file does not exist for fastq file it generates by tophat2 in the same directory
+# function for uploading generated bams by bam2bedgraph into genome browser
+#
 function upload_tophat_bed_mysql {
 
  do_tophat_bam
@@ -249,31 +303,50 @@ function do_bowtie_hits {
 function do_average {
  do_bw_bam "bam"
  do_bed_file "${NA}"
+ echo "do average not done yet"
+ exit 
  ${REPO_BASE}/genome-tools/ 
 }
 
 function do_sicer {
  do_bw_bam "bam"
-# do_bed_file "${NA}_s"
- bam2bedgraph -in="${NA}.bam" -out="${NA}_s.bed" -log="${NA}_s.log" -bed_window=1 -bed_format=4 -no-sql-upload
+
+ echo "do sicer not done yet"
+ exit 
+
+ T=1
+ W=200
+ G=200
+ E=100
+# LIMIT=8100000
+ if [ -f "./${NA}_s.bed" ]; then
+  echo "${NA}_s.bed exist"
+ else
+#  ${REPO_BASE}/genomebrowser/src/bam2bedgraph/bam2bedgraph -in="${NA}.bam" -out="${NA}_s.bed" -log="${NA}_s.log" -bed_window=0 -bed_format=8 -no-sql-upload -sam_mapped_limit=0
+#  grep -v 'track' ${NA}_s.bed|awk '{ if($4<0) $4=$4*(-1); printf("%s\t%s\t%s\tU%s\t%s\t%s\n",$1,$2,$3,$5,$4,$6);}' >${NA}_so.bed
+#  mv -f ${NA}_so.bed ${NA}_s.bed
+  if [ ${LIMIT} -gt 0 ]; then
+   bamToBed -bed12 -i ${NA}.bam |head -${LIMIT} >./${NA}_s.bed
+  else
+   bamToBed -bed12 -i ${NA}.bam >./${NA}_s.bed
+  fi
+ fi
 
 # if [ -f "./SICER/${NA}_s-W200-G0-E100.scoreisland" ]; then
 #  echo "./SICER/${NA}_s-W200-G0-E100.scoreisland exist"
- if [ -f "./SICER/${NA}_s-1-removed.bed" ]; then
-  echo "./SICER/${NA}_s-1-removed.bed exist"
+ if [ -f "./SICER/${NA}_s-W${W}-G${G}-E${E}.scoreisland" ]; then
+  echo "./SICER/${NA}_s-W${W}-G${G}-E${E}.scoreisland exist"
+  cd ./SICER
+  ${REPO_BASE}/genomebrowser/scripts/BedLoaderSicer.py ${NA} ${GROUP} hg19
+  cd ..
  else
-  if [ -f ${NA}_s.bed ]; then
-   echo "${NA}_s.bed exist"
-  else
-  grep -v 'track' ${NA}_s.bed|awk '{ if($4<0) $4=$4*(-1); printf("%s\t%s\t%s\tU%s\t%s\t%s\n",$1,$2,$3,$5,$4,$6);}' >${NA}_so.bed
-  mv -f ${NA}_so.bed ${NA}_s.bed
-  fi
   mkdirhier ./SICER/
-  sh ${REPO_BASE}/genome-tools/thirdparty/SICER1.1/SICER/SICER-rb.sh . ${NA}_s.bed ./SICER hg19 1 50 150 0.74 50 0.1 
+#  sh ${REPO_BASE}/genomebrowser/thirdparty/SICER1.1/SICER/SICER-rb.sh . ${NA}_s.bed ./SICER hg19 1 50 150 0.74 50 0.1
+  SICER-rb.sh . ${NA}_s.bed ./SICER hg19 ${T} ${W} 150 0.74 ${G} ${E}
  fi
  
 # cd ./SICER/
-# ${REPO_BASE}/genome-tools/scripts/BedLoaderScicer.py ${NA}_s ${GROUP} ${GENOME}
+# ${REPO_BASE}/genomebrowser/scripts/BedLoaderScicer.py ${NA}_s ${GROUP} ${GENOME}
 
 # sh /usr/src/SICER1.1/SICER/SICER-rb.sh . ${NA}.bed ./OUT hg19 1 200 150 0.74 0 100 &
 # mkdirhier /mnt/sf_G_DRIVE/FASTQ-DATA/results/${NA}/OUT
@@ -282,9 +355,9 @@ function do_sicer {
 # mkdirhier /mnt/sf_G_DRIVE/FASTQ-DATA/results/${NA}/OUT
 # grep -v 'track' output.bed|awk '{ if($4<0) $4=$4*(-1); printf("%s\t%s\t%s\tU%s\t%s\t%s\n",$1,$2,$3,$5,$4,$6);}' >/mnt/sf_G_DRIVE/FASTQ-DATA/results/${NA}/${NA}.bed
 # hg19 1 ["window size (bp)"] ["fragment size"] ["effective genome fraction"] ["gap size (bp)"] ["E-value"]
-# /usr/src/REPO/genome-tools/scripts/BedLoader.py ${NA}
+# /usr/src/REPO/genomebrowser/scripts/BedLoader.py ${NA}
 # cd /mnt/sf_G_DRIVE/FASTQ-DATA/results/${NA}/OUT/
-# /usr/src/REPO/genome-tools/scripts/BedLoaderScicer.py ${NA}
+# /usr/src/REPO/genomebrowser/scripts/BedLoaderScicer.py ${NA}
 # sh /usr/src/SICER1.1/SICER/SICER-rb.sh . ${NA}.bed ./OUT hg19 1 200 150 0.74 0 100 &
 }
 
@@ -321,42 +394,25 @@ function do_fence {
 # MAIN Function
 #
 
-if [ "${1}" == "" ]; then
-  echo "
- Programm usage:"
-  echo " 
- $0 -bedtophatmsql [LIST]
- $0 -dotophat [LIST]
- $0 -bedmsql [LIST]
- $0 -bedmsql_pair [LIST]
- $0 -bowtiehits [LIST]
- $0 -bowtiebam [LIST]
- $0 -dosicer [LIST]
- $0 -doquest [LIST]
- $0 -doaverage [LIST]
-  "
- exit 
-fi
 
-LST=${2}
-if [ "${LST}" == "" ]; then
- cd ${WORK_DIR}
+
+cd ${WORK_DIR}
  for i in `ls -c LIST*`; do
-  LST=${i}
+  export LST=${i}
   break
  done
+
 if [ "${LST}" == "" ]; then
- LST=./LIST
+ echo "Cannot find LIST with fastq files"
+ exit
 fi 
-fi
 
 
 # Create new file handle 5
 exec 5< ${LST}
 
-#for i in `grep -v '^#' ${LST}`; do
 while read i <&5 ; do
-# NA=`basename $i .bam` 
+#skeep lines started with #
 echo "${i}"|grep -v "^#" >/dev/null
 [ $? -eq 1 ] && continue
 
@@ -373,6 +429,7 @@ echo "${i}"|grep -v "^#" >/dev/null
  cd ${WORK_DIR} #/${NA}/
 
  #do_fence "${NA}"
+
 
 case ${1} in
   "-bedtophatmsql")
